# Generated by Django 5.1.7 on 2025-03-15 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField(help_text='完整的轉錄文本內容', verbose_name='完整文本')),
                ('language', models.CharField(default='zh-tw', help_text='轉錄辨識的語言', max_length=20, verbose_name='辨識語言')),
                ('processing_method', models.CharField(choices=[('whisper', 'OpenAI Whisper'), ('vosk', 'Vosk 本地引擎'), ('manual', '手動轉錄')], default='whisper', help_text='使用的轉錄引擎或模型', max_length=50, verbose_name='處理方法')),
                ('confidence_score', models.FloatField(blank=True, help_text='轉錄文本的整體信心分數 (0-1)', null=True, verbose_name='信心分數')),
                ('is_processed', models.BooleanField(default=False, help_text='是否已完成處理（包括講者辨識等）', verbose_name='處理完成')),
                ('word_count', models.PositiveIntegerField(default=0, help_text='轉錄文本的總字數', verbose_name='字數')),
                ('processing_time', models.FloatField(blank=True, help_text='轉錄處理所花費的時間(秒)', null=True, verbose_name='處理時間(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('audio_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='audio_manager.audiofile', verbose_name='音訊檔案')),
            ],
            options={
                'verbose_name': '轉錄文本',
                'verbose_name_plural': '轉錄文本',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(help_text='片段開始時間(秒)', verbose_name='開始時間(秒)')),
                ('end_time', models.FloatField(help_text='片段結束時間(秒)', verbose_name='結束時間(秒)')),
                ('text', models.TextField(help_text='該時間段的轉錄文本', verbose_name='文本內容')),
                ('speaker_id', models.CharField(blank=True, help_text='講者識別ID', max_length=50, null=True, verbose_name='講者ID')),
                ('speaker_name', models.CharField(blank=True, help_text='講者顯示名稱', max_length=100, null=True, verbose_name='講者名稱')),
                ('confidence', models.FloatField(blank=True, help_text='該片段的信心分數 (0-1)', null=True, verbose_name='信心分數')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='audio_manager.transcript', verbose_name='轉錄文本')),
            ],
            options={
                'verbose_name': '轉錄片段',
                'verbose_name_plural': '轉錄片段',
                'ordering': ['start_time'],
            },
        ),
    ]
