# Generated by Django 5.1.7 on 2025-03-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_manager', '0002_transcript_transcriptsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptsegment',
            name='is_manually_edited',
            field=models.BooleanField(default=False, help_text='是否被手動編輯過', verbose_name='手動編輯'),
        ),
        migrations.AddField(
            model_name='transcriptsegment',
            name='word_count',
            field=models.PositiveIntegerField(default=0, help_text='片段文本的字數', verbose_name='字數'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['transcript', 'speaker_id'], name='audio_manag_transcr_8ad33a_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['start_time', 'end_time'], name='audio_manag_start_t_ded9ee_idx'),
        ),
    ]
