# Generated by Django 5.1.7 on 2025-03-14 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan', models.CharField(choices=[('free', '免費版'), ('basic', '基礎版'), ('premium', '進階版')], default='free', max_length=20, verbose_name='訂閱計劃')),
                ('monthly_quota', models.JSONField(default=dict, help_text='每月使用配額', verbose_name='月度配額')),
                ('used_quota', models.JSONField(default=dict, help_text='已使用配額', verbose_name='已用配額')),
                ('api_key', models.CharField(blank=True, help_text='API 金鑰', max_length=100, verbose_name='API金鑰')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者配置檔',
                'verbose_name_plural': '使用者配置檔',
            },
        ),
    ]
